name: My first CI/CD pipeline

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Measuring Code Coverage
        run : |
             pip install coverage
             coverage run -m pytest
             coverage report
             coverage xml
      - name: Upoad to Codecov
        uses: codecov/codecov-action@v2
        with:
            file: coverage.xml

      - name: Lint Code
        run: pip install flake8 && flake8 .

      - name: Security Scan using Bandit
        run: | 
              pip install bandit
              bandit -r .

      - name: Build Docker Images
        run : docker build -t my-python-app .

      - name: Run Docker Images
        run : docker run my-python-app

    
